name: Sonar Scan

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

jobs:
  sonar:
    uses: ArmorCode-Public-Test/.github/workflows/sonar-template.yml@main
    with:
      projectKey: ${{ github.repository }}
